import type { Subject } from "./types";

export const subjects: Subject[] = [
  {
    id: "civil-engineering",
    name: "Civil Engineering",
    slug: "civil-engineering",
    chapters: [
      {
        id: "engineering-survey",
        code: "04",
        name: "Engineering Survey",
        slug: "engineering-survey",
        description: "Field measurement, surveying instruments, traversing, curves and quantity computation.",
        subtopics: [
          { id: "survey-4-1", code: "4.1", name: "INTRO & CLASSIFICATION", slug: "intro-classification", questionCount: 0 },
          { id: "survey-4-2", code: "4.2", name: "LINEAR MEASUREMENT", slug: "linear-measurement", questionCount: 0 },
          { id: "survey-4-3", code: "4.3", name: "COMPASS", slug: "compass", questionCount: 0 },
          { id: "survey-4-4", code: "4.4", name: "PLANE TABLE", slug: "plane-table", questionCount: 0 },
          { id: "survey-4-5", code: "4.5", name: "LEVELING", slug: "leveling", questionCount: 0 },
          { id: "survey-4-6", code: "4.6", name: "CONTOURING", slug: "contouring", questionCount: 0 },
          { id: "survey-4-7", code: "4.7", name: "THEODOLITE TRAVERSE", slug: "theodolite-traverse", questionCount: 0 },
          { id: "survey-4-8", code: "4.8", name: "TACHEOMETRY", slug: "tacheometry", questionCount: 0 },
          { id: "survey-4-9", code: "4.9", name: "TOTAL STATION", slug: "total-station", questionCount: 0 },
          { id: "survey-4-10", code: "4.10", name: "CURVES", slug: "curves", questionCount: 0 },
          { id: "survey-4-11", code: "4.11", name: "AREA & VOLUME", slug: "area-volume", questionCount: 0 },
        ],
      },
      {
        id: "construction-materials",
        code: "05",
        name: "Construction Materials",
        slug: "construction-materials",
        description: "Engineering properties and applications of stones, ceramics, cementing materials, metals and timber.",
        subtopics: [
          { id: "materials-5-1", code: "5.1", name: "MATERIAL PROPERTIES", slug: "material-properties", questionCount: 0 },
          { id: "materials-5-2", code: "5.2", name: "STONES", slug: "stones", questionCount: 0 },
          { id: "materials-5-3", code: "5.3", name: "CERAMIC MATERIALS", slug: "ceramic-materials", questionCount: 0 },
          { id: "materials-5-4", code: "5.4", name: "CEMENTING MATERIALS", slug: "cementing-materials", questionCount: 0 },
          { id: "materials-5-5", code: "5.5", name: "METALS", slug: "metals", questionCount: 0 },
          { id: "materials-5-6", code: "5.6", name: "TIMBER & WOOD", slug: "timber-wood", questionCount: 0 },
          { id: "materials-5-7", code: "5.7", name: "MISC MATERIALS", slug: "misc-materials", questionCount: 0 },
          { id: "materials-5-8", code: "5.8", name: "SOIL PROPERTIES", slug: "soil-properties", questionCount: 0 },
          { id: "materials-5-9", code: "5.9", name: "LOCAL & MODERN MATERIALS", slug: "local-modern-materials", questionCount: 0 },
        ],
      },
      {
        id: "concrete-technology",
        code: "06",
        name: "Concrete Technology",
        slug: "concrete-technology",
        description: "Concrete constituents, water-cement ratio, mix design, curing, admixtures and high-strength concrete.",
        subtopics: [
          { id: "concrete-6-1", code: "6.1", name: "CONCRETE CONSTITUENTS", slug: "concrete-constituents", questionCount: 0 },
          { id: "concrete-6-2", code: "6.2", name: "W-C RATIO", slug: "water-cement-ratio", questionCount: 0 },
          { id: "concrete-6-3", code: "6.3", name: "GRADE & MIX DESIGN", slug: "grade-mix-design", questionCount: 0 },
          { id: "concrete-6-4", code: "6.4", name: "MIXING & CURING", slug: "mixing-curing", questionCount: 0 },
          { id: "concrete-6-5", code: "6.5", name: "ADMIXTURES", slug: "admixtures", questionCount: 0 },
          { id: "concrete-6-6", code: "6.6", name: "HIGH STRENGTH CONCRETE", slug: "high-strength-concrete", questionCount: 0 },
          { id: "concrete-6-7", code: "6.7", name: "PRESTRESSED CONCRETE", slug: "prestressed-concrete", questionCount: 0 },
        ],
      },
      {
        id: "soil-mechanics",
        code: "07",
        name: "Soil Mechanics",
        slug: "soil-mechanics",
        description: "Soil formation, three-phase systems, water in soil, index properties and geotechnical fundamentals.",
        subtopics: [
          { id: "soil-7-1", code: "7.1", name: "SOIL FORMATION", slug: "soil-formation", questionCount: 0 },
          { id: "soil-7-2", code: "7.2", name: "3-PHASE SOIL", slug: "three-phase-soil", questionCount: 0 },
          { id: "soil-7-3", code: "7.3", name: "WATER IN SOIL", slug: "water-in-soil", questionCount: 0 },
          { id: "soil-7-4", code: "7.4", name: "INDEX PROPERTIES", slug: "index-properties", questionCount: 0 },
          { id: "soil-7-5", code: "7.5", name: "ROCK & EARTHQUAKE", slug: "rock-earthquake", questionCount: 0 },
          { id: "soil-7-6", code: "7.6", name: "TUNNELING", slug: "tunneling", questionCount: 0 },
        ],
      },
    ],
  },
];
